name: Alerta BPO

on:
  schedule:
    - cron: "*/2 * * * *"
  workflow_dispatch:
  push:
    branches:
      - principal
    paths:
      - 'enviados.csv'

jobs:
  run-alerta:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write

    steps:
      - name: Checkout do codigo
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar dependencias
        run: pip install pandas requests

      - name: Rodar script
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        run: python alerta_bpo.py

      - name: Salvar historico no GitHub
        run: |
          git config --global user.name "robo"
          git config --global user.email "bot@github.com"
          git add enviados.csv
          git commit -m "Atualizacao historica [skip ci]" || echo "Sem mudancas para salvar"
          git push
